//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3752.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/PurchaseOrderSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Square", Namespace="http://tempuri.org/PurchaseOrderSchema.xsd", IsNullable=false)]
public partial class SquareType {
    
    private int iWinnerField;
    
    private bool iWinnerFieldSpecified;
    
    private string chWinnerField;
    
    private int rowField;
    
    private bool rowFieldSpecified;
    
    private int columnField;
    
    private bool columnFieldSpecified;
    
    private int sectorField;
    
    private bool sectorFieldSpecified;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int iWinner {
        get {
            return this.iWinnerField;
        }
        set {
            this.iWinnerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool iWinnerSpecified {
        get {
            return this.iWinnerFieldSpecified;
        }
        set {
            this.iWinnerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chWinner {
        get {
            return this.chWinnerField;
        }
        set {
            this.chWinnerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int row {
        get {
            return this.rowField;
        }
        set {
            this.rowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rowSpecified {
        get {
            return this.rowFieldSpecified;
        }
        set {
            this.rowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int column {
        get {
            return this.columnField;
        }
        set {
            this.columnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool columnSpecified {
        get {
            return this.columnFieldSpecified;
        }
        set {
            this.columnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sector {
        get {
            return this.sectorField;
        }
        set {
            this.sectorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sectorSpecified {
        get {
            return this.sectorFieldSpecified;
        }
        set {
            this.sectorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}
